### ISSUE TITLE
Convert camera coordinates to EPSG:3857 (OpenLayers 3 internal) coordinates

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#25]
Pressing p currently prints the camera position to the Javascript console (PathControls.js onKeyDown()). The coordinate system of the camera position is unknown.

- [x] Find out what coordinate system Potree is using
- [x] Convert Potree system to EPSG:3857 (OpenLayers 3), EPSG:4326 (Google) or EPSG:32633 (system used in Laz files).

**Comment by Maartenvm** [comment]
Camera position in minimap and in the 3D world are now synchronized.
