### ISSUE TITLE
Coordinate system identification wrong in camerapath.json

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#28]
The crs name in data/camerapath.json is given as urn:ogc:def:crs:OGC:1.3:CRS84, while the feature coordinates are in fact in the (yet to be identified) POTree coordinate system (for which we do not know the crs name). The crs part of the object is not actually used anywhere.

Possible fixes:
- Either remove it altogether
- ... or find out what coordinate system we're using, put that in and actually do something with it in the code. See also issue #25 .

**Comment by sverhoeven** [comment]
Camera path can now be recorded using 'Record camera location' button in the Settings panel.
Must be manually added to `app/data/drivemap.json`.
The path is in the drivemap coordinate system.
