### ISSUE TITLE
Upgrade minimap based on Potree georeferencing example

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#31]
The new version of Potree contains a nice alternative example of a minimap. You can find it at bower_components/potree/examples/georeferencing.html.

A few components that we should copy from his implementation are:
- [x] The "camFrustrum", an arrow in the map that indicates the camera's position /and/ orientation.
- [x] With the implementation of a camera arrow, we can remove the current automatic recentering of the map based on camera location.
- [x] A bounding box around the point cloud area in the map. Could be based on the octree boundingbox, or on the actual points.

**Comment by sverhoeven** [comment]
Added arrow, when camera moves arrow also moves. 
Still need to recenter and reorient when rotating camera.

**Comment by sverhoeven** [comment]
Rotation and zoom of camera are also shown on minimap.

**Comment by Maartenvm** [comment]
We have a georeferenced minimap with footprints and historical maps now. I'd say this is done and done.

**Comment by nikhilbv** [comment]
@Maartenvm Hi, Can you please provide URL of georeferencing.html because I have no idea about this link - bower_components/potree/examples/georeferencing.html.

**Comment by nikhilbv** [comment]
Hi @egpbos ,
I have integrated to mapboxgl maps now. So I am curious to know if there is any way to bring this - 
1. The "camFrustrum", an arrow in the map that indicates the camera's position /and/ orientation.                         2. With the implementation of a camera arrow, we can remove the current automatic recentering of the map based on camera location.                        
3. A bounding box around the point cloud area in the map. Could be based on the octree boundingbox, or on the actual points.
to mapboxgl. Any leads would be appreciated.

**Comment by egpbos** [comment]
Sorry @nikhilbv, haven't worked on this for about 4 years, so I wouldn't know where to start.

**Comment by Jayasshree** [comment]
Hi..
Can you now provide the solution for the above problem @egpbos .

**Comment by Jayasshree** [comment]
I want to correlate between mapboxgl map camera position with the pointcloud data in potree.
Any help in this regard.

**Comment by egpbos** [comment]
Unfortunately, I won't be able to help, @Jayasshree, it's been too long for me to quickly remember and I have other commitments now.
