### ISSUE TITLE
Highlight SiteBoxes when searched for

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#42]
Default behaviour for SiteBoxes is to be invisible until the user hovers over them with the mouse pointer. It might be nice that they become highlighted (e.g. with some colored wireframe) when they are part of the search results from the search box.

This could be implemented in a similar way to the way the site-outlines are displayed on the minimap. They are also updated based on the search results. This is done by adding the filtered sites to the Angular watch list (in minimap/minimap.controller.js).

- [ ] First fix #43!
- [ ] Implement this!

**Comment by Maartenvm** [comment]
Done. Siteboxes are now also filtered.
