### ISSUE TITLE
Help documentation for user interface (incomplete)

### ISSUE THREAD

**Issue by lodekulik** [NLeSC/PattyVis#48]
User Interface

General

(gear-icon) Settings
Access point-cloud settings

Navigation

(heli-icon) Fly Navigation
ASDW or Arrows: Move freely through scene
Mouse: rotate camera

(indiana-icon) First-Person Navigation
WS: Move back and forth in first-person view
Mouse: rotate camera

(play-icon) Play Mode
Automically move along a preconfigured demo path

Measurement

(toolkit-icon) Toolkit
Click to open measuring instruments

(distance-icon) Distance
Left Mouse: Insert Measurement Point
Right Mouse: Finish insertion
Drag&Drop: Move Measurement Points

Distance between measurement points will be displayed on the edge.

(area-icon) Surface Area
Left Mouse: Insert Measurement Point
Right Mouse: Finish insertion
Drag&Drop: Move Measurement Points

Distance between measurement points will be displayed on the edge and the total area on the centroid. The area is calculated on the ground plane. The height does not affect the result. Crossings should be avoided.

(volume-icon) Volume
Left Mouse: Insert Volume or Select Inserted Volume
Switch between translation (icon), scale (icon) and rotation (icon) mode

Keyboard shortcut: E, R, T

Volume will be displayed on the objects centroid.

(hightprofile-icon) Height Profile
Left Mouse: Insert Profile Marker
Right Mouse: Finish insertion
Drag&Drop: Move Profile Marker
ctrl + Drag&Drop: Drag upwards to increase or downwards to decrease the profile width

Depending on the Clip Mode, points inside the profile will be highlighted or points outside the profile will be clipped.

(clipvolume-icon) Clip Volume
Left Mouse: Insert Volume or Select Inserted Volume
Switch between translation (icon), scale (icon) and rotation (icon) mode

Keyboard shortcut: E, R, T

**Comment by Maartenvm** [comment]
Help documentation is implemented.
