### ISSUE TITLE
Units in measurement tools

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#50]
- [ ] We should add (physical) units to the measurements. Distances in meters, surface areas in m^2, volumes in m^3 or liters or something like that.
- [ ] Inches/feet/yards conversion option
- [ ] Other historical units conversion option (e.g. "ancient foot")
- [ ] Angles in radians or $a \pi$ option?

**Comment by egpbos** [comment]
At the e-Rome conference, a participant indeed suggested that adding historical units ("ancient foot") conversion would be very useful.

**Comment by Maartenvm** [comment]
The units are set inside the potree library and only transmitted as images. This makes changing this tricky, as it would require a complete fork of the measurement tools and a subsequent reworking. Making them less compatible with future versions of potree. We therefore decided not to do this for now.
