### ISSUE TITLE
Make elements (mainly minimap) resizable or with on/off switch

### ISSUE THREAD

**Issue by egpbos** [NLeSC/PattyVis#56]
Especially at lower resolutions (e.g. when using older beamers) the minimap blocks a too great part of the 3D scene view (see attached image).

![patty-lowres](https://cloud.githubusercontent.com/assets/6146598/6502967/bd50104c-c328-11e4-8c21-10204908316a.JPG)

It would be good to add a on/off switch for the minimap, or at least resize it based on resolution.

Also, the buttons are quite big when used in a low resolution. Maybe we could resize those as well, or switch them on/off with a single small button.

**Comment by Maartenvm** [comment]
I agree these things would be really important if we had more time ...

(also... holy moly how old is that beamer?)
